### ISSUE TITLE
Error when installing plugin

### ISSUE THREAD

**Issue by arknoll** [ThomasFarmer/PotreeCraft#1]
I get the following "Couldn't load plugin 'potreecraft" error:

Couldn't load plugin 'potreecraft' due to an error when calling its classFactory() method 

ImportError: DLL load failed: The specified module could not be found. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/alexknoll/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\potreecraft\__init__.py", line 36, in classFactory
    from .potreecraft_util import PotreeCraftSupport
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/alexknoll/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\potreecraft\potreecraft_util.py", line 7, in 
    import win32file
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified module could not be found.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.9-A Coruña A Coruña, bf47e9d3e1 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/alexknoll/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/alexknoll/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/alexknoll/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by ThomasFarmer** [comment]
Hello @arknoll ,
Thanks for the post, i got the same error as i tried to do it now, i'll look into this.
Tom

**Comment by ThomasFarmer** [comment]
Ok the issue was with the win32 library import, which is not used anymore anyway, i just commented it out. you can now install the plugin by downloading the new build zip. It looks hideous under ubuntu, but as you can see it works for me now:
![Screenshot from 2020-08-25 14-58-58pluginworks](https://user-images.githubusercontent.com/23472718/91177228-ae08d300-e6e3-11ea-8c75-1f263ae7ba4d.png)

**Comment by ThomasFarmer** [comment]
closing issue due to complete overhaul of the project.
